server:
  port: 7002

eureka:
  instance:
    hostname: eureka7002.com
  client:
    # false means that this is not a eureka server
    register-with-eureka: false
    # false means that this is not a eureka client
    fetch-registry: false
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/