server:
  port: 7001

eureka:
  instance:
    hostname: eureka7001.com
  client:
    # false means that this is not a eureka server
    register-with-eureka: false
    # false means that this is not a eureka client
    fetch-registry: false
    service-url:
      defaultZone: http://eureka7002.com:7002/eureka/